"""empty message

Revision ID: 6bf73303e448
Revises: 
Create Date: 2021-03-16 12:59:24.932784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf73303e448'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping-cart',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping-cart')
    # ### end Alembic commands ###
