"""empty message

Revision ID: be1785c9b44c
Revises: 
Create Date: 2021-03-20 18:58:18.206324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be1785c9b44c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_cart',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_cart')
    # ### end Alembic commands ###
